import React from "react";

/**
 * Example Figma SVG component.
 *
 * In a real workflow, this file would be generated by the Figma MCP
 * `get_design_context` tool. You provide a Figma URL and it outputs
 * a React component with the design's SVG/HTML structure.
 *
 * Key points:
 * - Elements that should be animated get `id` or `className` attributes
 *   matching their Figma layer names
 * - Group elements (`<g>`) correspond to Figma groups
 * - Add `ref` props to elements you want to target with GSAP
 */
export const ExampleDesign: React.FC<{
  logoRef?: React.Ref<SVGGElement>;
  titleRef?: React.Ref<SVGTextElement>;
  subtitleRef?: React.Ref<SVGTextElement>;
  shapesRef?: React.Ref<SVGGElement>;
}> = ({ logoRef, titleRef, subtitleRef, shapesRef }) => {
  return (
    <svg
      width="1920"
      height="1080"
      viewBox="0 0 1920 1080"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      {/* Background gradient */}
      <defs>
        <linearGradient id="bgGradient" x1="0" y1="0" x2="1920" y2="1080">
          <stop offset="0%" stopColor="#0f0f23" />
          <stop offset="100%" stopColor="#1a1a3e" />
        </linearGradient>
        <linearGradient id="accentGradient" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stopColor="#6366f1" />
          <stop offset="100%" stopColor="#8b5cf6" />
        </linearGradient>
      </defs>

      <rect width="1920" height="1080" fill="url(#bgGradient)" />

      {/* Decorative shapes group */}
      <g
        ref={shapesRef}
        id="decorative-shapes"
        style={{ transformOrigin: "center center", transformBox: "fill-box" }}
      >
        <circle cx="200" cy="200" r="120" fill="#6366f1" opacity="0.15" />
        <circle cx="1700" cy="300" r="80" fill="#8b5cf6" opacity="0.12" />
        <circle cx="300" cy="800" r="60" fill="#a78bfa" opacity="0.1" />
        <rect
          x="1500"
          y="700"
          width="200"
          height="200"
          rx="20"
          fill="#6366f1"
          opacity="0.08"
          transform="rotate(15, 1600, 800)"
        />
      </g>

      {/* Logo group */}
      <g
        ref={logoRef}
        id="logo"
        style={{ transformOrigin: "center center", transformBox: "fill-box" }}
      >
        <rect
          x="860"
          y="280"
          width="200"
          height="200"
          rx="40"
          fill="url(#accentGradient)"
        />
        <path
          d="M920 340 L960 420 L1000 340 L980 340 L960 380 L940 340 Z"
          fill="white"
        />
        <circle cx="960" cy="410" r="15" fill="white" opacity="0.9" />
      </g>

      {/* Title text */}
      <text
        ref={titleRef}
        id="title"
        x="960"
        y="560"
        textAnchor="middle"
        fill="white"
        fontSize="72"
        fontFamily="Inter, system-ui, sans-serif"
        fontWeight="700"
      >
        Figma to Video
      </text>

      {/* Subtitle text */}
      <text
        ref={subtitleRef}
        id="subtitle"
        x="960"
        y="630"
        textAnchor="middle"
        fill="#a5b4fc"
        fontSize="28"
        fontFamily="Inter, system-ui, sans-serif"
        fontWeight="400"
      >
        Powered by Remotion + GSAP
      </text>
    </svg>
  );
};
